# This is a basic workflow to help you get started with Actions

name: Try it

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  try_for_self:
    name: Try install for self
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run install_CNS11643_fonts_ubuntu.sh
        run: ./install_CNS11643_fonts_ubuntu.sh
        shell: bash
      - name: Assert has Kai font
        run: fc-list | grep TW-Kai-
      - name: Assert has Sung font
        run: fc-list | grep TW-Sung-
  
  try_for_all:
    name: Try install for all users
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run install_CNS11643_fonts_ubuntu_for_all_user.sh
        run: ./install_CNS11643_fonts_ubuntu_for_all_user.sh
        shell: bash
      - name: Assert has Kai font
        run: fc-list | grep TW-Kai-
      - name: Assert has Sung font
        run: fc-list | grep TW-Sung-
